# Generated by Django 5.0.4 on 2024-10-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proa', '0003_logro_noticia_rename_titulo_evento_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
